"""Entry/exit rules.

Mean-reversion on RSI:
  ENTRY (green) - RSI crosses back ABOVE the oversold line: selling pressure is exhausting.
  EXIT  (red)   - RSI crosses back BELOW the overbought line: the rally is losing momentum.

Signals are generated by a two-state machine (flat <-> long), so entries and exits always
alternate and the chart never shows two greens in a row.
"""

import pandas as pd

ENTRY, EXIT = "entry", "exit"


def crossed_above(series: pd.Series, level: float) -> pd.Series:
    return (series.shift(1) < level) & (series >= level)


def crossed_below(series: pd.Series, level: float) -> pd.Series:
    return (series.shift(1) > level) & (series <= level)


def generate_signals(df: pd.DataFrame, oversold: float, overbought: float) -> pd.DataFrame:
    """Return one row per signal: date, type, close, rsi, reason."""
    want_entry = crossed_above(df["rsi"], oversold)
    want_exit = crossed_below(df["rsi"], overbought)

    rows, in_position = [], False
    for ts in df.index:
        if not in_position and want_entry.loc[ts]:
            in_position = True
            rows.append((ts, ENTRY, f"RSI crossed above {oversold:g} (oversold rebound)"))
        elif in_position and want_exit.loc[ts]:
            in_position = False
            rows.append((ts, EXIT, f"RSI crossed below {overbought:g} (overbought fade)"))

    sig = pd.DataFrame(rows, columns=["date", "type", "reason"])
    if sig.empty:
        return sig.assign(close=[], rsi=[])
    sig = sig.set_index("date")
    sig["close"] = df.loc[sig.index, "close"]
    sig["rsi"] = df.loc[sig.index, "rsi"]
    return sig.reset_index()


def position_series(index: pd.DatetimeIndex, signals: pd.DataFrame) -> pd.Series:
    """1 while long, 0 while flat. A signal on day t is acted on at the close of day t,
    so the position earns returns from t+1 onward (no look-ahead bias)."""
    if signals.empty:
        return pd.Series(0.0, index=index)
    marks = signals.set_index("date")["type"].map({ENTRY: 1.0, EXIT: 0.0})
    held = pd.Series(float("nan"), index=index)
    held.loc[marks.index] = marks
    return held.ffill().fillna(0.0).shift(1).fillna(0.0)
